# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'demo.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(806, 605)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(610, 10, 161, 194))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_controll = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_controll.setObjectName("pushButton_controll")
        self.verticalLayout.addWidget(self.pushButton_controll)
        self.pushButton_camera = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_camera.setObjectName("pushButton_camera")
        self.verticalLayout.addWidget(self.pushButton_camera)
        self.pushButton_unlock = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_unlock.setObjectName("pushButton_unlock")
        self.verticalLayout.addWidget(self.pushButton_unlock)
        self.pushButton_lock = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_lock.setObjectName("pushButton_lock")
        self.verticalLayout.addWidget(self.pushButton_lock)
        self.pushButton_stopcontroll = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_stopcontroll.setObjectName("pushButton_stopcontroll")
        self.verticalLayout.addWidget(self.pushButton_stopcontroll)
        self.pushButton_stopcamera = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_stopcamera.setObjectName("pushButton_stopcamera")
        self.verticalLayout.addWidget(self.pushButton_stopcamera)
        self.pushButton_face = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_face.setGeometry(QtCore.QRect(600, 470, 181, 31))
        self.pushButton_face.setObjectName("pushButton_face")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(630, 220, 121, 21))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 40, 491, 481))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(610, 260, 161, 201))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setEnabled(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_5.addWidget(self.label)
        self.Scrollbar_pitch = QtWidgets.QScrollBar(self.layoutWidget)
        self.Scrollbar_pitch.setOrientation(QtCore.Qt.Horizontal)
        self.Scrollbar_pitch.setObjectName("Scrollbar_pitch")
        self.verticalLayout_5.addWidget(self.Scrollbar_pitch)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.Scrollbar_roll = QtWidgets.QScrollBar(self.layoutWidget)
        self.Scrollbar_roll.setOrientation(QtCore.Qt.Horizontal)
        self.Scrollbar_roll.setObjectName("Scrollbar_roll")
        self.verticalLayout_5.addWidget(self.Scrollbar_roll)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.Scrollbar_yaw = QtWidgets.QScrollBar(self.layoutWidget)
        self.Scrollbar_yaw.setOrientation(QtCore.Qt.Horizontal)
        self.Scrollbar_yaw.setObjectName("Scrollbar_yaw")
        self.verticalLayout_5.addWidget(self.Scrollbar_yaw)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_5.addWidget(self.label_4)
        self.Scrollbar_thrust = QtWidgets.QScrollBar(self.layoutWidget)
        self.Scrollbar_thrust.setOrientation(QtCore.Qt.Horizontal)
        self.Scrollbar_thrust.setObjectName("Scrollbar_thrust")
        self.verticalLayout_5.addWidget(self.Scrollbar_thrust)
        self.pushButton_set = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_set.setObjectName("pushButton_set")
        self.verticalLayout_5.addWidget(self.pushButton_set)
        self.pushButton_stopface = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_stopface.setGeometry(QtCore.QRect(600, 510, 181, 31))
        self.pushButton_stopface.setObjectName("pushButton_stopface")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 806, 25))
        self.menubar.setObjectName("menubar")
        self.menuMore = QtWidgets.QMenu(self.menubar)
        self.menuMore.setObjectName("menuMore")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuMore.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "UAV controller"))
        self.pushButton_controll.setText(_translate("MainWindow", "launch controll node"))
        self.pushButton_camera.setText(_translate("MainWindow", "launch camera"))
        self.pushButton_unlock.setText(_translate("MainWindow", "unlock UAV"))
        self.pushButton_lock.setText(_translate("MainWindow", "lock UAV"))
        self.pushButton_stopcontroll.setText(_translate("MainWindow", "stop controll node"))
        self.pushButton_stopcamera.setText(_translate("MainWindow", "stop camera node"))
        self.pushButton_face.setText(_translate("MainWindow", "face detect and trace"))
        self.label_5.setText(_translate("MainWindow", "manual controll"))
        self.label_6.setText(_translate("MainWindow", "video"))
        self.label.setText(_translate("MainWindow", "pitch"))
        self.label_2.setText(_translate("MainWindow", "roll   "))
        self.label_3.setText(_translate("MainWindow", "yaw  "))
        self.label_4.setText(_translate("MainWindow", "thrust"))
        self.pushButton_set.setText(_translate("MainWindow", "boot"))
        self.pushButton_stopface.setText(_translate("MainWindow", "stop face detect"))
        self.menuMore.setTitle(_translate("MainWindow", "more"))

